version: "3.9"

services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: sleep infinity
    depends_on:
      - spanner
    # - spanner-emulator
    env_file:
      - .env

  spanner:
    image: gcr.io/cloud-spanner-emulator/emulator
    ports:
      - "9010:9010" # gRPC
      - "9020:9020" # HTTP

  # spanner-emulator:
