x-spanner-id-vars: &spanner-id-vars
  SPANNER_PROJECT_ID: ${SPANNER_PROJECT_ID}
  SPANNER_INSTANCE_ID: ${SPANNER_INSTANCE_ID}
  SPANNER_DATABASE_ID: ${SPANNER_DATABASE_ID}
  SPANNER_EMULATOR_HOST: spanner-emulator:9010

x-app-common: &app-common
  ports:
    - "${APP_PORT}:${APP_PORT}"
  volumes:
    - .:/usr/src/app
  working_dir: /usr/src/app
  depends_on:
    - spanner-emulator
  environment:
    <<: *spanner-id-vars

services:
  app-dev:
    <<: *app-common
    profiles: ["dev"]
    build:
      context: .
      dockerfile: docker/app.dev.Dockerfile
    command: air
    restart: unless-stopped

  app-build:
    <<: *app-common
    profiles: ["build"]
    build:
      context: .
      dockerfile: docker/app.build.Dockerfile
    restart: always

  spanner-emulator:
    image: gcr.io/cloud-spanner-emulator/emulator
    restart: always
    ports:
      - "9010:9010"
      - "9020:9020"
    environment:
      <<: *spanner-id-vars
  
  spanner-init:
    image: google/cloud-sdk:slim
    depends_on:
      - spanner-emulator
    volumes:
      - ./scripts:/scripts
    entrypoint: ["/bin/bash", "/scripts/spanner-init.sh"]
    restart: on-failure
    environment:
      <<: *spanner-id-vars
      CLOUDSDK_API_ENDPOINT_OVERRIDES_SPANNER: http://spanner-emulator:9020/

  wrench-migrate:
    build:
      context: .
      dockerfile: docker/wrench.Dockerfile
    depends_on:
      spanner-init:
        condition: service_completed_successfully
    volumes:
      - ./db:/usr/src/app/db
      - ./scripts:/scripts
    working_dir: /usr/src/app
    entrypoint: ["/bin/sh", "/scripts/wrench-migrate.sh"]
    restart: no
    environment:
      <<: *spanner-id-vars