x-env: &env
  env_file:
    - .env

services:
  app-dev:
    profiles: ["dev"]
    build:
      context: .
      dockerfile: docker/app.dev.Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: air
    restart: unless-stopped
    depends_on:
      - spanner-emulator
    <<: *env

  app-build:
    profiles: ["build"]
    build:
      context: .
      dockerfile: docker/app.build.Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    restart: always
    depends_on:
      - spanner-emulator
    <<: *env

  spanner-emulator:
    image: gcr.io/cloud-spanner-emulator/emulator
    restart: always
    ports:
      - "9010:9010"
      - "9020:9020"
    <<: *env
  
  spanner-init:
    image: google/cloud-sdk:slim
    depends_on:
      - spanner-emulator
    volumes:
      - ./scripts:/scripts
    entrypoint: ["/bin/bash", "/scripts/spanner-init.sh"]
    restart: on-failure
    environment:
      - SPANNER_EMULATOR_HOST=spanner-emulator:9010
      - CLOUDSDK_API_ENDPOINT_OVERRIDES_SPANNER=http://spanner-emulator:9020/
    <<: *env

  atlas-migrate:
    build:
      context: .
      dockerfile: docker/atlas.Dockerfile
    depends_on:
      spanner-init:
        condition: service_completed_successfully
    environment:
      - ATLAS_NO_LOGIN=1
      - SPANNER_EMULATOR_HOST=spanner-emulator:9010
    volumes:
      - ./scripts:/scripts
      - ./db:/usr/src/app/db
      - ./atlas.hcl:/usr/src/app/atlas.hcl
    working_dir: /usr/src/app
    entrypoint: ["/bin/bash", "/scripts/atlas-run.sh"]
    restart: no
    <<: *env